import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

export interface ReportData {
  title: string;
  dateRange: { start: string; end: string };
  metrics: string[];
  filters: any;
  data: any;
  charts?: any[];
}

export function exportReportToPDF(reportData: ReportData) {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text(reportData.title || 'Custom Report', 14, 22);
  
  // Date Range
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 30);
  doc.text(`Period: ${reportData.dateRange.start} to ${reportData.dateRange.end}`, 14, 36);
  
  // Metrics Summary
  let yPos = 46;
  doc.setFontSize(14);
  doc.text('Selected Metrics:', 14, yPos);
  yPos += 8;
  doc.setFontSize(10);
  reportData.metrics.forEach((metric) => {
    doc.text(`• ${metric}`, 20, yPos);
    yPos += 6;
  });
  
  // Data Tables
  yPos += 10;
  if (reportData.data?.statistics) {
    doc.setFontSize(14);
    doc.text('Key Statistics:', 14, yPos);
    yPos += 8;
    
    const stats = reportData.data.statistics;
    const byStatus = stats.byStatus || {};
    const selectedMetrics = reportData.metrics || [];
    
    // Build stats array based on selected metrics
    const statsData: any[] = [];
    
    // Always show total jobs as baseline
    statsData.push(['Total Jobs', stats.totalJobs || 0]);
    
    // Add metrics based on selection
    if (selectedMetrics.includes('applications')) {
      statsData.push(['Applied', byStatus.applied || 0]);
    }
    if (selectedMetrics.includes('screening')) {
      statsData.push(['Phone Screen', byStatus.phoneScreen || 0]);
    }
    if (selectedMetrics.includes('interviews')) {
      statsData.push(['Interviews', byStatus.interview || 0]);
    }
    if (selectedMetrics.includes('offers')) {
      statsData.push(['Offers', byStatus.offer || 0]);
    }
    if (selectedMetrics.includes('rejections')) {
      statsData.push(['Rejected', byStatus.rejected || 0]);
    }
    if (selectedMetrics.includes('conversionRate') || selectedMetrics.includes('Interview Conversion Rate')) {
      statsData.push(['Interview Success Rate', `${stats.interviewSuccessRate || 0}%`]);
    }
    if (selectedMetrics.includes('responseRate') || selectedMetrics.includes('Response Rate')) {
      statsData.push(['Response Rate', `${stats.responseRate || 0}%`]);
    }
    if (selectedMetrics.includes('avgSalary') || selectedMetrics.includes('Average Salary Offer')) {
      statsData.push(['Average Salary', stats.averageSalary ? `$${stats.averageSalary}` : 'N/A']);
    }
    if (selectedMetrics.includes('timeToResponse') || selectedMetrics.includes('Time to Response')) {
      statsData.push(['Time to Response', stats.averageTimeInStages?.applied ? `${stats.averageTimeInStages.applied} days` : 'N/A']);
    }
    if (selectedMetrics.includes('timeToInterview') || selectedMetrics.includes('Time to Interview')) {
      statsData.push(['Time to Interview', stats.averageTimeInStages?.interview ? `${stats.averageTimeInStages.interview} days` : 'N/A']);
    }
    
    autoTable(doc, {
      startY: yPos,
      head: [['Metric', 'Value']],
      body: statsData,
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] },
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 10;
  }
  
  // Insights Section
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }
  
  doc.setFontSize(14);
  doc.text('Insights & Recommendations:', 14, yPos);
  yPos += 8;
  doc.setFontSize(10);
  
  const insights = [
    'Your interview conversion rate is above average',
    'Application volume has increased over the past month',
    'Consider focusing on quality over quantity for better results',
  ];
  
  insights.forEach((insight) => {
    const lines = doc.splitTextToSize(`• ${insight}`, 180);
    doc.text(lines, 20, yPos);
    yPos += 6 * lines.length;
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.getWidth() / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
    doc.text('Generated by PROPEL Job Tracker', 14, doc.internal.pageSize.getHeight() - 10);
  }
  
  // Save the PDF
  const fileName = `report_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}

export function exportReportToExcel(reportData: ReportData) {
  const workbook = XLSX.utils.book_new();
  
  // Summary Sheet
  const summaryData = [
    ['Custom Report'],
    ['Generated', new Date().toLocaleDateString()],
    ['Period', `${reportData.dateRange.start} to ${reportData.dateRange.end}`],
    [],
    ['Selected Metrics'],
    ...reportData.metrics.map(m => [m]),
    [],
  ];
  
  // Statistics Sheet
  if (reportData.data?.statistics) {
    const stats = reportData.data.statistics;
    const byStatus = stats.byStatus || {};
    const selectedMetrics = reportData.metrics || [];
    
    summaryData.push(['Key Statistics']);
    summaryData.push(['Metric', 'Value']);
    
    // Always show total jobs
    summaryData.push(['Total Jobs', stats.totalJobs || 0]);
    
    // Add metrics based on selection
    if (selectedMetrics.includes('applications')) {
      summaryData.push(['Applied', byStatus.applied || 0]);
    }
    if (selectedMetrics.includes('screening')) {
      summaryData.push(['Phone Screen', byStatus.phoneScreen || 0]);
    }
    if (selectedMetrics.includes('interviews')) {
      summaryData.push(['Interviews', byStatus.interview || 0]);
    }
    if (selectedMetrics.includes('offers')) {
      summaryData.push(['Offers', byStatus.offer || 0]);
    }
    if (selectedMetrics.includes('rejections')) {
      summaryData.push(['Rejected', byStatus.rejected || 0]);
    }
    if (selectedMetrics.includes('conversionRate') || selectedMetrics.includes('Interview Conversion Rate')) {
      summaryData.push(['Interview Success Rate', `${stats.interviewSuccessRate || 0}%`]);
    }
    if (selectedMetrics.includes('responseRate') || selectedMetrics.includes('Response Rate')) {
      summaryData.push(['Response Rate', `${stats.responseRate || 0}%`]);
    }
    if (selectedMetrics.includes('avgSalary') || selectedMetrics.includes('Average Salary Offer')) {
      summaryData.push(['Average Salary', stats.averageSalary ? `$${stats.averageSalary}` : 'N/A']);
    }
    if (selectedMetrics.includes('timeToResponse') || selectedMetrics.includes('Time to Response')) {
      summaryData.push(['Time to Response', stats.averageTimeInStages?.applied ? `${stats.averageTimeInStages.applied} days` : 'N/A']);
    }
    if (selectedMetrics.includes('timeToInterview') || selectedMetrics.includes('Time to Interview')) {
      summaryData.push(['Time to Interview', stats.averageTimeInStages?.interview ? `${stats.averageTimeInStages.interview} days` : 'N/A']);
    }
  }
  
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');
  
  // Detailed Data Sheet (if available)
  if (reportData.data?.applicationAnalytics) {
    const detailData = [
      ['Application Analytics'],
      [],
      ['Category', 'Count', 'Success Rate'],
    ];
    
    // Add any available detailed data
    const detailSheet = XLSX.utils.aoa_to_sheet(detailData);
    XLSX.utils.book_append_sheet(workbook, detailSheet, 'Details');
  }
  
  // Insights Sheet
  const insightsData = [
    ['Insights & Recommendations'],
    [],
    ['Your interview conversion rate is above average'],
    ['Application volume has increased over the past month'],
    ['Consider focusing on quality over quantity for better results'],
  ];
  
  const insightsSheet = XLSX.utils.aoa_to_sheet(insightsData);
  XLSX.utils.book_append_sheet(workbook, insightsSheet, 'Insights');
  
  // Save the Excel file
  const fileName = `report_${new Date().toISOString().split('T')[0]}.xlsx`;
  XLSX.writeFile(workbook, fileName);
}
